### ISSUE TITLE
[Bug]: Creation of Geometry objects from other geometry objects not working

### ISSUE THREAD

**Issue by arpit15** [Peter-van-Tol/pydantic-shapely#10]
### Initial Checks

- [X] I confirm that I'm using Pydantic V2

### Description

Creation of a class containing annotated `MultiPolygon` fails with a list of `Polygon`  with validation error. Hopefully this behavior could be supported by changing validation logic in `GeometryField` 

**Error**
```
Traceback (most recent call last):
  File "/home/username/coding_bits/pydantic_checks/pydantic_checks/check_shapely.py", line 33, in <module>
    obj = MyClass(polys=[Polygon(shell=((0.0, 0.0), (0.0, 1.0), (1.0, 1.0), (1.0, 0.0)))])
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/username/coding_bits/pydantic_checks/.venv/lib/python3.11/site-packages/pydantic/_internal/_dataclasses.py", line 134, in __init__
    s.__pydantic_validator__.validate_python(ArgsKwargs(args, kwargs), self_instance=s)
pydantic_core._pydantic_core.ValidationError: 1 validation error for MyClass
polys
  Value error, Supplied string is not a valid WKT-string [type=value_error, input_value=[<POLYGON ((0 0, 0 1, 1 1, 1 0, 0 0))>], input_type=list]
    For further information visit https://errors.pydantic.dev/2.5/v/value_error
```

### Example Code

```Python
from shapely import MultiPolygon, Polygon
from pydantic_shapely import GeometryField
from pydantic.dataclasses import dataclass

@dataclass
class MyClass:
    polys: Annotated[MultiPolygon, GeometryField()]

mpoly = MultiPolygon([Polygon(shell=((0.0, 0.0), (0.0, 1.0), (1.0, 1.0), (1.0, 0.0)))])
assert isinstance(mpoly, MultiPolygon)

obj = MyClass(polys=MultiPolygon([
    (
    ((0.0, 0.0), (0.0, 1.0), (1.0, 1.0), (1.0, 0.0)),
    [((0.1,0.1), (0.1,0.2), (0.2,0.2), (0.2,0.1))]
    )
]))

obj = MyClass(polys=[Polygon(shell=((0.0, 0.0), (0.0, 1.0), (1.0, 1.0), (1.0, 0.0)))])
```
```


### Python, Pydantic, Shapely & OS Version

```Text
Pydantic-shapely version: 1.0.0a2
Shapely version: 2.0.6
             pydantic version: 2.5.3
        pydantic-core version: 2.14.6
          pydantic-core build: profile=release pgo=true
                 install path: /home/username/coding_bits/pydantic_checks/.venv/lib/python3.11/site-packages/pydantic
               python version: 3.11.4 (main, Aug 14 2023, 05:19:15) [GCC 7.5.0]
                     platform: Linux-6.8.0-40-generic-x86_64-with-glibc2.35
             related packages: typing_extensions-4.12.2
```
```

**Comment by arpit15** [comment]
I am wondering if there is any suggestion on this. Without updating the dependencies, I am afraid I can't use this library.

**Comment by Peter-van-Tol** [comment]
Thank you for considering to us this library. I'll be able to change the validators this weekend. I hope that this will be quick enough fornyour project.

**Comment by Peter-van-Tol** [comment]
Fixed in version `1.0.0a3`, available on PyPi now! 🚀

**Comment by Peter-van-Tol** [comment]
It is merged to main, however the upload to pypi has failed. Will resolve tomorrow morning.

**Comment by Peter-van-Tol** [comment]
Mistake while pushing the updated `pyproject.toml`. The version has now been successfully uploaded to PyPi:

![image](https://github.com/user-attachments/assets/4f16c0cb-7921-4b2f-ad79-e5750dfd6d7a)
